# Generated by Django 3.0 on 2020-11-17 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0004_auto_20201117_0025'),
        ('art', '0004_auto_20201117_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='organization',
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(default='', max_length=200, verbose_name='Location name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aboutme.Education', verbose_name='School where project was performed'),
        ),
    ]
