# Generated by Django 3.0 on 2020-11-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0007_auto_20201117_0123'),
        ('art', '0005_auto_20201117_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(to='experience.Skill'),
        ),
    ]
