# Generated by Django 3.0 on 2020-11-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0007_auto_20201117_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='embedHTML',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='iframe or HTML to embed within thumbnail'),
        ),
    ]
