# Generated by Django 3.0 on 2020-11-19 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0008_project_embedhtml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='art.Media'),
        ),
    ]
