# Generated by Django 3.0 on 2020-11-19 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0009_auto_20201119_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='media',
            name='format',
        ),
    ]
