# Generated by Django 3.0 on 2020-11-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0011_auto_20201119_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='art/'),
        ),
    ]
