# Generated by Django 3.0 on 2020-11-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
