# Generated by Django 3.0 on 2020-11-19 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='fullname',
        ),
    ]
