# Generated by Django 3.0 on 2020-11-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_remove_contact_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalWebsites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_link', models.URLField()),
                ('icon', models.ImageField(null=True, upload_to='icons/')),
                ('display_link', models.CharField(max_length=50)),
            ],
        ),
    ]
