# Generated by Django 3.0 on 2020-11-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_externalwebsites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalwebsites',
            name='display_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
