# Generated by Django 3.0 on 2020-11-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='external_link',
            field=models.URLField(blank=True, verbose_name='External link to website with detailed info'),
        ),
    ]
