# Generated by Django 3.0 on 2020-11-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0007_auto_20201117_0123'),
        ('science', '0002_auto_20201117_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(related_name='scienceSkill', to='experience.Skill'),
        ),
    ]
