# Generated by Django 3.0 on 2020-11-17 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0003_project_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created on this website')),
                ('date_modified', models.DateTimeField(auto_now_add=True, verbose_name='Date changed on this website')),
                ('date_recorded', models.DateField(verbose_name='Day media was recorded')),
                ('file_name', models.CharField(max_length=200, verbose_name='File Name')),
                ('format', models.CharField(max_length=10, verbose_name="File format ('.jpeg', '.mp3' ...)")),
                ('upload', models.ImageField(blank=True, null=True, storage='./media', upload_to='./media')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='science.Media'),
        ),
    ]
