# Generated by Django 3.0 on 2020-11-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0005_auto_20201117_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='media',
            name='format',
        ),
        migrations.AlterField(
            model_name='media',
            name='upload',
            field=models.ImageField(blank=True, null=True, storage='images/', upload_to='images/'),
        ),
    ]
