# Generated by Django 3.0 on 2020-11-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0006_position_thumbnail_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50, verbose_name='Skill name')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='skills',
            field=models.ManyToManyField(to='experience.Skill'),
        ),
    ]
