# Generated by Django 3.0 on 2020-11-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0007_auto_20201117_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='color',
            field=models.CharField(choices=[('red', 'FF4845'), ('blue', '4E93FF'), ('grey', '686668'), ('green', '24A944'), ('orange', 'FFA051')], default='#000', max_length=40),
        ),
    ]
