# Generated by Django 3.0 on 2020-11-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0008_skill_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='color',
            field=models.CharField(choices=[('#FF4845', 'red'), ('#4E93FF', 'blue'), ('#686668', 'grey'), ('#24A944', 'green'), ('#FFA051', 'orange')], default='#000', max_length=40),
        ),
    ]
