# Generated by Django 3.0 on 2020-11-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0009_auto_20201117_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='color',
            field=models.CharField(choices=[('#ff4845', 'red'), ('#4e93ff', 'blue'), ('#686668', 'grey'), ('#24a944', 'green'), ('#ffa051', 'orange')], default='#000', max_length=40),
        ),
    ]
