# Generated by Django 3.0 on 2020-11-16 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='date_graduated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, max_length=100, verbose_name='Date Degree obtained'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='date_started',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, max_length=100, verbose_name='Date education started'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.CharField(default='', max_length=100, verbose_name='Courses/skills used for degree'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(default='', max_length=100, verbose_name='Degree obtained'),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(default='', max_length=100, verbose_name='School Name'),
        ),
    ]
