# Generated by Django 3.0 on 2020-11-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_auto_20201116_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date_graduated',
            field=models.DateField(max_length=100, verbose_name='Date Degree obtained'),
        ),
        migrations.AlterField(
            model_name='education',
            name='date_started',
            field=models.DateField(max_length=100, verbose_name='Date education started'),
        ),
    ]
