# Generated by Django 3.0 on 2020-11-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0003_auto_20201117_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.CharField(default='', max_length=2000, verbose_name='Courses/skills used for degree'),
        ),
    ]
